baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.highlight]
codeFences = true
style = "dracula"
#style = "rrt"
#style = "solarized-dark"
#style = "solarized-dark256"
#style = "vim"
#style = "native"
#style = "paraiso-dark"
tabWidth = 2
lineNoStart = 1
lineNos = false

[params.reveal_hugo]
highlight_theme = "atom-one-dark"
custom_theme = "custom-theme.scss"
custom_theme_compile = true

[params.reveal_hugo.custom_theme_options]
targetPath = "css/custom-theme.css"
enableSourceMap = true